### ISSUE TITLE
dash case events and case sensitive events

### ISSUE THREAD

**Issue by MathieuPuech** [BBKolton/reactify-wc#14] opened 2020-08-11 18:36 UTC
Dash case events are working with current implementation but you need to implement like that:

```jsx
<SomeComponent
  onEvent-with-dash={handler} />
```

Developers could think it will be dispatched on `onEventWithDash`. I don't know if it's an issue.

Another issue is that events types are case sensitive (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener). I suppose it's not possible to listen to 2 differents events with different case.

Example of case sensitive events:

```javascript
document.body.addEventListener('test', console.log);
document.body.dispatchEvent(new CustomEvent('test')); // logged
document.body.dispatchEvent(new CustomEvent('Test')); // not logged
```

**Comment by brion-fuller** [comment] 2021-07-27 17:56
I am not sure what we can do for helping the format of dash events.  The onName syntax I believe is a JSX detail around determining event bindings.  Do you have any thoughts for this?

I believe by default events are case sensitive.  I would believe this is intended behavior.

**Comment by brion-fuller** [comment] 2021-07-29 17:38
I will close this issue for now.  Feel free to respond and reopen.

**Closed by brion-fuller** 2021-07-29 17:38 UTC
